# Introducción a NumPy

NumPy es una librería que nos permite trabajar con __arrays__. 

## ¿Qué es un array? 

Un array es un __bloque de memoria que contiene elementos del mismo tipo__. Básicamente:

* Misma estructura que las listas, con la diferencia de que en un array, __sus elementos tienen que ser del mismo tipo__
* Podemos almacenar el array con un nombre y acceder a sus __elementos__ mediante sus __índices__.
* Ayudan a gestionar de manera eficiente la memoria y a acelerar los cálculos.


---

| Índice     | 0     | 1     | 2     | 3     | ...   | n-1   | n  |
| ---------- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Valor      | 2.1   | 3.6   | 7.8   | 1.5   | ...   | 5.4   | 6.3 |

---

__Los array son ideales para almacenar valores numéricos con los cuales deseamos realizar determinadas operaciones aritmetico lógicas. Para estas tareas llegan incluso a ser más eficientes que las listas convecionales de Python__

## ¿Qué es NumPy?

NumPy es un paquete fundamental para la programación científica que __proporciona un objeto tipo array__ para almacenar datos de forma eficiente y una serie de __funciones__ para operar y manipular esos datos.
Para usar NumPy lo primero que debemos hacer es importarlo (y vamos a darle un alias, np):

In [2]:
import numpy as np
# Para ver la versión que tenemos instalada:
np.__version__

'1.20.1'

## Nuestro primer array

In [ ]:
# Array de una dimensión
nums = [1, 2, 3, 4]
mi_primer_array = np.array(nums) 

In [ ]:
# Podemos usar print
print(mi_primer_array)

In [ ]:
# Comprobar el tipo de mi_primer_array
print(type(mi_primer_array))

# Comprobar el tipo de datos que contiene
print(mi_primer_array.dtype)

Los arrays de una dimensión se crean pasándole una lista como argumento a la función `np.array`. Para crear un array de dos dimensiones le pasaremos una lista de listas:

In [ ]:
# Array de dos dimensiones
mi_segundo_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

En ocasiones, es un lío escribirlo todo en una línea, por lo que podemos escribirlo en líneas separadas, siempre y cuando cuidemos el formato. Esto sería una buena manera de definirlo, de acuerdo con el [PEP 8 (indentation)](http://legacy.python.org/dev/peps/pep-0008/#indentation):

In [ ]:
mi_segundo_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
    ]) 
print(mi_segundo_array)

### Funciones y constantes de NumPy

NumPy también incorporá __funciones__. Un ejemplo sencillo:

In [ ]:
# Suma
print(np.sum(mi_primer_array))

In [ ]:
# Máximo
print(np.max(mi_primer_array))

In [ ]:
# Seno
print(np.sin(mi_segundo_array))

Y algunas __constantes__ que podemos neccesitar:

In [ ]:
print(np.pi)
print(np.e)

## Funciones para crear arrays

#### array de ceros

In [ ]:
# En una dimensión
a = np.zeros(100)
print(a)

In [ ]:
# En dos dimensiones
a = np.zeros([10,10])
print(a)

#### array "vacío"

In [ ]:
a = np.empty(10)
print(a)

<div class="alert alert-error"><strong>Importante:</strong> 
El array vacío se crea en un tiempo algo inferior al array de ceros. Sin embargo, el valor de sus elementos será arbitrario y dependerá del estado de la memoria. Si lo utilizas asegúrate de que luego llenas bien todos sus elementos porque podrías introducir resultados erróneos.
</div>

#### array de unos

In [ ]:
a = np.ones([3, 2])
print(a)

<div class="alert alert-info"><strong>Nota:</strong> 
Otras funciones muy útiles son `np.zeros_like` y `np.ones_like`. Usa la ayuda para ver lo que hacen si lo necesitas.
</div>

#### array identidad

In [3]:
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.eye()` y `np.diag()`.
</div>

### Rangos

#### np.arange

Generar rangos de que __un array vaya de 0 a 5__:

In [4]:
a = np.arange(0, 5)
print(a)

[0 1 2 3 4]


Generar rangos de que __un array vaya de 0 a 10, de 3 en 3__:

In [ ]:
a = np.arange(0, 11, 3)
print(a)

#### np.linspace

Con linspace se generan valores espaciados linealmente

In [ ]:
a = np.linspace(0, 10, 25) # inicio, fin, num_resultados
print(a)

<div class="alert alert-info"><strong>Nota:</strong> 
También puedes probar `np.logspace()`
</div>

### reshape

Con `np.arange()` es posible crear "vectores" cuyos elementos tomen valores consecutivos o equiespaciados, como hemos visto anteriormente. ¿Podemos hacer lo mismo con "matrices"? Pues sí, pero no usando una sola función. Imagina que quieres crear algo como esto:

\begin{pmatrix}
    1 & 2 & 3\\ 
    4 & 5 & 6\\
    7 & 8 & 9\\
    \end{pmatrix}
    
* Comenzaremos por crear un array 1d con los valores $(1,2,3,4,5,6,7,8,9)$ usando `np.arange()`.
* Luego le daremos forma de array 2d. con `np.reshape(array, (dim0, dim1))`.

In [5]:
a = np.arange(1, 10)
m = np.reshape(a, [3, 3])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# También funciona como método
m = a.reshape([3,3])
print(m)

## Operaciones

### Operaciones elemento a elemento

In [12]:
# crear un array y sumarle un número
a = np.arange(11)
print(a)
a = a + 55
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[55 56 57 58 59 60 61 62 63 64 65]


In [13]:
# multiplicarlo por un número
a = a * 2
print(a)

[110 112 114 116 118 120 122 124 126 128 130]


In [14]:
# elevarlo al cuadrado
a = a ** 2
print(a)

[12100 12544 12996 13456 13924 14400 14884 15376 15876 16384 16900]


__Si las operaciones involucran dos arrays también se realizan elemento a elemento__

In [7]:
#creamos dos arrays
arr1 = np.arange(0, 11)
arr2 = np.arange(20, 31)
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30]


In [8]:
#los sumamos
arr3 = arr1 + arr2
print(arr3)

[20 22 24 26 28 30 32 34 36 38 40]


In [9]:
#multiplicamos
arr3 = arr1 * arr2
print(arr3)

[  0  21  44  69  96 125 156 189 224 261 300]


#### Comparaciones

In [10]:
# >,<
arr3 = arr1 > arr2
print(arr3)

[False False False False False False False False False False False]


In [11]:
# ==
arr3 = arr1 == arr2 # ¡ojo! los arrays son de integers, no de floats
print(arr3)

[False False False False False False False False False False False]
